name: Auto Issue

on:
  schedule:
    - cron: "0 18 * * *"  # Runs daily at 03:00 JST
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.AUTO_APPROVER_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title":"Auto-created issue","body":"This issue was created automatically."}' 
