name: Auto Merge Status

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    name: automerge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "✅ This job makes the 'automerge' status check pass"